# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: oai-tutorial
service:
  name: oai-flexric
  port: 36421
  type: NodePort
  node_port: 31234 #must be within range 30000 - 32767
image:
  repository: docker.io/oaisoftwarealliance/oai-flexric
  tag: develop
configmap_data:
  flexric_conf: |-
    [NEAR-RIC]
    NEAR_RIC_IP = 0.0.0.0
    [XAPP]
    DB_DIR = /tmp/

multus:
  interface:
    create: true
    ipAdd: "172.21.6.210"
    netmask: "22"
    gateway: "172.21.7.254"
    hostInterface: "eth0"
