apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oai-flexric.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-du.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oai-flexric.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-flexric
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.service.name }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
      containers:
        - name: {{ .Values.service.name }}
          securityContext: {}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/flexric/flexric.conf
              subPath: flexric_conf