{{- if .Values.multus.interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: oai-flexric
  namespace: {{ .Values.namespace }}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "{{ .Values.multus.interface.hostInterface }}",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "{{ .Values.multus.interface.ipAdd }}/{{ .Values.multus.interface.netmask }}",
          {{- if .Values.multus.interface.gateway }}
          "gateway": "{{ .Values.multus.interface.gateway }}"
          {{- end }}
        }
      ]
    }
  }'
{{- end }}
