apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oai-flexric.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: SCTP
      name: sctp
      nodePort: {{ .Values.service.node_port }}
  selector:
      {{- include "oai-flexric.selectorLabels" . | nindent 4 }}
